### ISSUE TITLE
Portal Network uTP layer

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#149]
Separate "Portal Network uTP" logic from uTP Protocol.  

uTP should be agnostic of content streamed.
Tracking of open content requests and offers should happen on client level.

Solution is new `PortalNetworkUTP` class that takes portal client as a constructor, and handles intermediate logic between client and uTP protocol.

**Comment by holgerd77** [comment]
Not sure, can this be *so* generic that we eventually could offer this as a general-purpose JavaScript/TypeScript utility class (respectively: package)? 🤔 Just thinking loudly. 😄

**Comment by acolytec3** [comment]
> Not sure, can this be *so* generic that we eventually could offer this as a general-purpose JavaScript/TypeScript utility class (respectively: package)? 🤔 Just thinking loudly. 😄 

I'd have to let Scotty comment on how doable that is but in not sure if there's any benefit. There's already at least one `node-utp` library out there and this is such a specialized use case that I can't imagine there are other UDP use cases out there that need this sort of second layer implementation of uTP that is abstracted away from the actual udp socket management.

**Comment by holgerd77** [comment]
Ah ok, thanks for the background here 👍

**Comment by acolytec3** [comment]
Fixed by #153
