### ISSUE TITLE
Portal Network Info / Links

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#182]
Add some basic "What is Portal Network?" type info and github links and such to the app.

Also add some directions in the app for how to use and what to do.  Same info as the README, but as an on screen tutorial of sorts.

One example of this is already present.  The ENR and ADDNODE fields have some information about what they are and what to do.  

* Links to PortalNetwork projects and specs
* "What is portal network"?  type Q&A's
* On screen directions for using the app, connecting to networks, etc.

**Comment by acolytec3** [comment]
Is there anything else you want to add? #183 felt like "good enough" for now.
