### ISSUE TITLE
Refactor `portalnetwork` client module

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#193]
The `portalnetwork`'s `client.ts` is overly complex right now and really is an implementation of the wire spec coupled tightly together with the History Subnetwork since that's all we support at present.  Some steps have been taken to generalize our implementation (see #140 as an example) but there likely remains some improvements to make things easier to reason about.  At a minimum, we should do the following:
- [x] Spec out an architectural diagram (maybe using MermaidJS since github supports it natively)  There is a PR #204 that has a good start on these.
- [ ] Look through each of the wire spec messages and see if there is complexity that can be abstracted out to make reasoning about each one easier - partially addressed with #251 to move the protocols into their own classes with message handlers
  - [ ] Work on adding additional simplification to SENDFINDCONTENT flow
- [ ] Look at the content and node lookup classes to see if there's improvements to be made in how that code is written/commented since it's quite involved as it attempts to implement the Kademlia lookup.
  - [ ] See if it's possible to abstract out POKE (OFFERing content to nodes who should have had content but didn't)
- [ ] Look at the uTP implementation again and think through its packaging to see if it can be further simplified since its a complex beast to reason through

**Comment by holgerd77** [comment]
I guess it will also hep to start on a second network implementation (or at least do the basic scaffolding) beside History Network to get a better feeling on the common ground between the networks.

**Comment by acolytec3** [comment]
> I guess it will also hep to start on a second network implementation (or at least do the basic scaffolding) beside History Network to get a better feeling on the common ground between the networks.

Agree.  I know that Trin and Fluffy at one point had started on the State Network (which would be really interesting to incorporate here since we could show a really powerful use case on mobile by looking up current account balances and contract states.  I'll ask in our implementers call today about where we go from here.
