### ISSUE TITLE
Improve CI jobs

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#230]
The current CI jobs install all the packages for the monorepo and then run tests that only need `portalnetwork` and `proxy`.  We should revise the current unit and integration workflows to only install the dependencies needed for those two packages and then build them and run the tests.

**Comment by ScottyPoi** [comment]
One consideration here might be upgrading to `actions/setup-node@v3`.
https://github.com/marketplace/actions/setup-node-js-environment

**Comment by ScottyPoi** [comment]
It seems like you should be able to do:
```
run: npm install
   working-directory: ./packages/proxy
```
But no matter what i try, it ends up doing the whole pre-install / post-install thing.

**Comment by ScottyPoi** [comment]
re: #260 

I see you had a similar journey?

**Comment by acolytec3** [comment]
😬 Yeah.... I've been trying to figure out how to not install all the dependencies for the browser client every time we do a ci run did it's a complete waste of time and electrons since we aren't testing the browser client
