### ISSUE TITLE
Persistent node identity

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#241]
Our discv5 implementations requires a peerId that contains an secp256k1 keypair which is used to sign the ENR that is then broadcasted by the discv5 client whenever establishing a new session.  That said, the original keypair is not stored within the discv5 client and the consuming application is expected to main that peerId and its associated keypair in order to preserve node identity across restarts.

In our `portalnetwork` module, with #239, we are now writing this peerId as JSON into the provided `levelDB` that is part of the `portalnetwork` constructor and then it's used in `recreatePortalNetwork` to restart the client with the previous peerID and routing table contents. The question to consider is whether its wise to store this peerId and its contents in a plaintext format in the DB.  In the browser environment, there is some possibility, though likely remote, that this keypair could be compromised by malware.  My reading on `IndexedDB` which is the web storage layer used by our `browser-client` db, says that it's limited to same origin CORS rules so should be as "safe" as anything else stored in browser storage that's not specifically encrypted.  

There may be better ways to do this that don't require storing private keys in our DB but given our use case where keys are probably ephemeral anyway and we're not signing anything other than an ENR, I'm thinking we're okay for now but we should revisit this again as the Portal Network project progresses.

**Comment by ScottyPoi** [comment]
we could serialize the peerId as a seialized SSZ container, and it would simply look like an arbitrary byte string in the `indexeddb`

**Comment by ScottyPoi** [comment]
`indexeddb` is a `leveldb` backed part of local storage.

`browser-level` is using the browser's `indexeddb`, but using the `leveldb` API

**Comment by ScottyPoi** [comment]
```
encrypt the peerId bytestring with a password and then (use) the same process to decrypt it if the password parameter is provided.
```

`password` is hardcoded into client.ts?  or somehow chosen by user?

**Comment by acolytec3** [comment]
What I was thinking was we could add a new optional parameter to the constructor for a password and use that as an encryption key.  I'd need to find the correct function in the `webcrypto` api but there should be a way to relatively easily do it without bringing in a new package.

**Comment by acolytec3** [comment]
https://www.perimeterx.com/tech-blog/2019/fun-times-with-webcrypto-part2/  Here's one example.  Maybe slightly more complex than I originally thought but this would do the trick.  Let's punt on this for now unless you're eager to get into it.

**Comment by acolytec3** [comment]
Closing this for now as I believe we have sufficient means available between `nodejs` and `browser` contexts to persist node identity.
