### ISSUE TITLE
`ContentAdded` event

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#254]
The `ContentAdded` event is emitted by the `client` whenever content is added to the database.  Currently, this is just used by the `HistoryProtocol`.  As we start to store more content types, this event needs to be rethought as to whether it should be emitted by the client or if we should think about adding event emitters at the `Protocol` level .

**Comment by acolytec3** [comment]
Probably. I've also started to consider a universal event bus like we use in the ethjs client. We're starting to multiply event emitters internally (see #255) and my instinct says it would be better in the long run to have one place where we manage events rather than across multiple subclasses. This needs to be a consideration as we further refine our structural refactor started in #251.

**Comment by holgerd77** [comment]
> Probably. I've also started to consider a universal event bus like we use in the ethjs client.

Yeah, that might be a good idea.

**Comment by acolytec3** [comment]
We need to take this one a bit more seriously, now that we have multiple event listeners getting created between `getBlockByHash` and `getBlockByNumber`.  One thought is to move the entire content lookup process to `contentLookup` so it only returns a valid serialized piece of content or else undefined.  Then, we could add a destructor (for lack of a better word) method that gets called that would clean up the listener and wouldn't have to keep track of them elsewhere.
