### ISSUE TITLE
Implement `eth_getLogs` endpoint

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#315]
Not 100% sure what all goes into this but at a minimum:
- [ ] Add support for transaction receipts to history network
- [ ] Look at EthereumJS client and see how getLogs is implemented
- [ ] Build out some sort of canonicalIndex for transaction -> block mapping
- [ ] Add `getTransactionReceipt` to history protocol
- [ ] Add `getLogs` method to history protocol
- [ ] Integrate `getTransactionReceipt` and `getLogs` in browser and cli clients

cc: @ScottyPoi this will serve as our tracking issue for receipts/logs.  Feel free to add/update/whatever or comment here as we learn more

**Comment by ScottyPoi** [comment]
I started working it out in the browser client and came to similar conclusions.

Is the idea, generally, that the network will store receipts individually by transaction hash?  Or are we trying to store whole blocks worth of receipts?

**Comment by acolytec3** [comment]
No, per [this][(https://github.com/ethereum/portal-network-specs/blob/master/history-network.md#receipts) the receipts are stored per block.  So if a block has transactions, there should be a corresponding list of receipts that are passed around the network as one blob of data encoded per the typing in the spec.

**Comment by acolytec3** [comment]
I'ma vote to close this one for now.  We're a long way from being able to support this on any reasonable context.
