### ISSUE TITLE
Update Test Suite

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#323]
Meta issue to improve testing for all packages.  

Checklist includes current test scripts to review and missing tests to build.  Check off as each one is revisited / revised / written.  

- [ ] Client
  - [ ] client.spec.ts
    - `node initialization/startup`
    - `cleanup`
- [ ] Wire
  - [ ] types.spec.ts
    - `message encoding`
  - [ ] **wire.spec.ts?** 
  - [x] utp
    - [x] `utp/packet.spec.ts`
    - [x] `utp/basic.spec.ts`
    - [x] `utp/socket.spec.ts`
    - [x] `utp/utp.spec.ts`
    - [x] `utp/util.spec.ts`    

- [ ] Util
  - [ ]  util.spec.ts
    - [ ] 'utility method tests'
      - `shortId()`
      - `generateRandomNodeIdAtDistance()`
- [ ] Subprotocols
  - [ ] protocol.spec.ts
  - [ ] history
    - [ ] headerAccumulator.spec.ts
      - `Validate accumulator updates`
    - [ ] historyProtocol.spec.ts
      -  `Message handler tests`
    - [ ] types.spec.ts
      - `content key serialization / deserialization`
    - [ ] util.spec.ts
      -  `utility functions`
      - `BlockBody ssz serialization / deserialization
  - [ ] state
    - [ ] utils.spec.ts
      - `distance()`
- [ ] Integration
  - [ ] wire.spec.ts
    - [x] `clients start and connect to each other`
    - [x] 'findContent should return a block header'
    - [x] 'findContent should return a block body'
    - [x] 'Offer / Accept should exchange block headers and bodies'
    - [x] 'findContent should return a header accumulator snapshot'
    - [x] 'findContent should return an epoch accumulator snapshot'
    - [x] 'history protocol should gossip with offer / accept'
    - [x] 'eth_getBlockByHash should return a full block'
    - [x] 'eth_getBlockByHash should return a block with header when no block body is found.
    - [x] 'eth_getBlockByNumber should return a block from the current_epoch
    - [x] 'eth_getBlockByNumber should return a block from a historical_epoch

- [ ] Another general todo is to run all of these tests using `karma-typescript` as well so we validate they work in browser.  Will add as a specific PR.

**Comment by ScottyPoi** [comment]
#313 
adds 
- `uTP protocol test`
- uTP reader/writer test`

**Comment by ScottyPoi** [comment]
#331  refactors wire / utp test suite.
removes:
* `utp.spec.ts`
adds:
* `utp/packet.spec.ts`
* `utp/basic.spec.ts`
* `utp/socket.spec.ts`
* `utp/utp.spec.ts`
* `utp/util.spec.ts`

**Comment by ScottyPoi** [comment]
This is what I get if I run `npx karma start ./karma.config.cjs`.  
![image](https://user-images.githubusercontent.com/66335769/185034745-d6d0c81f-b5f0-47a6-9ce6-8a5c2b3ed1f6.png)

**Comment by acolytec3** [comment]
Same here. It may just be that karma really won't work with our code being ESM modules. I've tried a few different tracks to get it working and never gotten past this. I might give up on karma and try another tool. There are other tools that will run tape in the browser as well
