### ISSUE TITLE
Add log filtering for browser client

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#353]
We should come up with a log filter widget that will easily allow us to filter the logging by various topics.  Under the hood should use `portal.enableLog('*Portal...`

**Comment by ScottyPoi** [comment]
Filtering by topic/protocol (wire, history, state, uTP...)  would be useful, as well as the usual sort of logging-level choices like:
```
{
  error: 0,
  warn: 1,
  info: 2,
  goldilocks: 3,
  verbose: 4,
  debug: 5,
  silly: 6
}
```

I hesitate to inflate our code with tons of debug calls.  This may just be personal preference, but I try to avoid long files that stretch much over ~200 lines.  I would want to engineer a way to infuse our methods with multi-level logging potential while keeping the code succinct and navigable.

**Comment by acolytec3** [comment]
Eh
