### ISSUE TITLE
DB returns empty array for keys instead of undefined

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#391]
While researching a fix in #390, @ScottyPoi noted that the DB sometimes returns empty `uint8Array`s instead of undefined.  We should research why the DB is returning an empty array since we should not be storing keys with empty array values.  It may be as simple as there is some instance where we are getting or computing an empty value for some content and storing it when we shouldn't.

**Comment by acolytec3** [comment]
@ScottyPoi is this still an issue?

**Comment by ScottyPoi** [comment]
I do not think so.
