### ISSUE TITLE
No standard discovery port

### ISSUE THREAD

**Issue by perama-v** [ethereumjs/ultralight#393]
## Problem description
Ultralight and Trin clients both use port 9000 for discovery, which clashes with Ethereum consensus clients as raised here:
 https://github.com/ethereum/trin/issues/487

It may be good to converge on port 9009, which Fluffy already uses by default.

**Comment by holgerd77** [comment]
Seems to make sense to me?

**Comment by ScottyPoi** [comment]
No argument from us.  
9000 was just a default on our end as well.

**Comment by ScottyPoi** [comment]
Actually our approach has always been to default to randomly assigned port numbers.  We could ban the use of port 9000 (and other known conflicts) to avoid clashes.

We do use `9000` in some some of the CLI client `dev` mode and test scripts, which I'm happy to change.  Is there something else I am missing where we have 9000 as a default?

**Comment by perama-v** [comment]
Ok, that's interesting. I was thinking from the perspective of writing setup guides, where the user is configuring a firewall. 

https://github.com/ethereum/trin/blob/master/docs/ubuntu_guide.md#configure-firewall

So if the discovery port is new on startup, the approach of specifying a single port would not work. 
I can, however, see that manually specifying ports may not be required in all environments/platforms.

**Comment by holgerd77** [comment]
I think it would make sense to at least have the option (on the Ultralight side) to set the port as not random? Or switch to a default port and rather make the random choice a CL parameter or something? Not sure about the needs/wants, just spreading some ideas here. Would just assume from a user perspective a fixed (default) port - with the option to explicitly set to something else - is always a good idea.

Maybe default port to 9009, and then allow initializing (or via CLI or whatever) with `port=12345` and also `port=random`? Again, all just ideas, pick the stuff that's feasible from your perspective.

**Comment by acolytec3** [comment]
This is handled via the `--bindAddress=1.2.3.4:9009` in our `cli` app.  Happy to discuss further if everyone wants a default not covered by the current setup.
