### ISSUE TITLE
uTP `contentWriter` race condition

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#398]
The [`eth_getBlockByNumber`](https://github.com/ethereumjs/ultralight/blob/06d69100116528758f0df200770261375fdbf24b/packages/portalnetwork/test/integration/integration.spec.ts#L207) integration test fails occasionally with this sort of issue:
![image](https://user-images.githubusercontent.com/17355484/216639322-be547534-f75d-44c6-be38-4b548ad53779.png)

The `contentWriter.start` method seems to occasionally get stuck if the `cur_window` and `max_window` values aren't updated on the correct tick.  We could explore reworking `contentWriter.start` away from recursively calling itself to use something like:

```
for (const chunk of chunks) {
   await sendPacket
```
or
```
for await (const chunk of chunks) {
   sendPacket
   next()
```

**Comment by ScottyPoi** [comment]
I don't think it can be that simple and follow the congestion control rules of uTP.

we can't just stream out packets.  There is supposed to be a limit of 3 in-flight packets, meaning data packets that have been sent but the ack not yet received. 

we're supposed to recalculate the round-trip time stuff for each packet, and use that metric to set a timeout function that is supposed to consider a packet lost if it is taking longer than expected.

we have to watch for ack / selective ack, and use that to stay no more than 3 packets ahead, while also resending packets that may have been lost.

I agree that the writer could be written differently, or better, or optimized, but it's never going to be as simple as `for (chunk of chunks) { sendChunk }`
