### ISSUE TITLE
uTP: Bad format of selective ack extension

### ISSUE THREAD

**Issue by kdeme** [ethereumjs/ultralight#403]
When testing data injection / gossip in the testnet I've noticed invalid behaviour of Ultralight nodes on the selective ack extension.

In the received packet header the extension flag is enabled, however the length of the extension data for selective ack is invalid.

Fluffy log message:
```
WRN 2023-03-14 14:45:17.250+01:00 Failed to decode packet from address       topics="eth utp utp_discv5_protocol" address="(nodeId: dedfdee9cfe1d391f17ad84652cca1e4cdb2d0cb113189dab98564d44bfc31e1, address: 164.92.247.243:5005)" msg="Packet too short for selective ack extension: 23 bytes"
```

Amount of bytes indicated is `23`.
Minimum amount of bytes must be `26` when selective ack is set.

Why?
- Default without extension, the header is `20` bytes .
- When an extension is added, there is additionally the next extension byte + the `len` of this extension => + `2` bytes
- Next, there are the extension payload bytes (according to previous `len`). For the selective ack it is written in the spec: "Its payload is a bitmask of at least 32 bits, in multiples of 32 bits.", thus => + `4` bytes, + `8` bytes, etc.

Hence, 23 cannot be valid.

Additional logging:
Returned raw data: `[33, 1, 110, 244, 0, 0, 57, 8, 0, 0, 0, 0, 0, 0, 4, 176, 84, 224, 147, 251, 0, 1, 251]`
Decoded header part: `(pType: ST_STATE, version: 1, extension: 1, connectionId: 28404, timestamp: 14600, timestampDiff: 0, wndSize: 1200, seqNr: 21728, ackNr: 37883)`

Additional note: In fluffy we actually only implement / allow the bitmask of 4 bytes, and nothing bigger, as it is what the reference implementation also did. Assumption here is that this is enough for the amount of packet in flight.

**Comment by acolytec3** [comment]
@kdeme are you still seeing this?

**Comment by kdeme** [comment]
> @kdeme are you still seeing this?

I've checked the logs of our fleet, I'm no longer seeing this error. So this can be closed.

I am however seeing another one: `msg="Bad format of selective ack extension: extension = 0 len = 8"`. But this is not invalidating the spec. It has to do with us only supporting one 4 byte bit mask.
