### ISSUE TITLE
State Network Development

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#406]
- [x] State Network Scaffolding #402 
- [ ] Database Refactor #407 
- [x] JSON RPC #409 #489
- [x] Wire Spec Refactor #408 
- [x] uTP Refactor #408 
- [x] StateProtocol methods #489 
  - [x] Store / Retrieve #407
  - [x] send/handle FindContent
  - [x] send/handle OFFER
  - [x] Gossip
- [ ] Unit testing
- [ ] Integration Test
- [x] CLI devnet #489

**Comment by acolytec3** [comment]
Lets close this and start fresh.
