### ISSUE TITLE
Decouple modules from HistoryNetwork types

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#408]
`Base Protocol` and much of the `Wire` module needs to be decoupled from the history network in a few ways.
Certain things were designed based on assumptions that are no longer valid with the new content types.
ProtocolId.HistoryNetwork is passed as a necessary parameter in methods that should be agnostic of the protocol that called them.  

May require a general refactor of wire spec to better generalize things.

- Types should be made generic, extended by sub-protocols
- Methods should be generalized.
- wire / utp Modules should be agnostic of Protocol specifics

**Comment by acolytec3** [comment]
A lot of this is tackled in #440 (at least with regard to uTP and the `BaseProtocol`).  There's probably some very crafty Typescript ways of making the content types navigable by protocol ID without introducing giant switch statements in every place we have to multiplex between subprotocols but I haven't figured it out yet.

**Comment by acolytec3** [comment]
Going to close this.  I've seen what happens when you try to make giant namespace types to handle stuff and let's just leave it at `switches`.
