### ISSUE TITLE
docs: statement appears incorrect 

### ISSUE THREAD

**Issue by ltfschoen** [ethereumjs/ultralight#447]
in the IDiscv5 docs it says _"Nodes return the external IP address that they have received and a simple majority is chosen as our external IP address."_ but that statement doesn't seem to make sense? 
how is our external IP address chosen from a simple majority, what does that mean?

https://github.com/ethereumjs/ultralight/blame/master/packages/portalnetwork/docs/interfaces/IDiscv5CreateOptions.md#L12

**Comment by acolytec3** [comment]
This is cribbed from the `discv5` design.  The actual implementation happens within the [`@chainsafe/discv5` package](https://github.com/ChainSafe/discv5/blob/master/src/service/addrVotes.ts).  The "votes" are the IP address and port reported by discv5 PONG messages as described [here](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#pong-response-0x02).

**Comment by acolytec3** [comment]
Closing this issue for now.  If you have any further questions, please let  me know!
