### ISSUE TITLE
Add a cli flag to specify the amount of storage

### ISSUE THREAD

**Issue by KolbyML** [ethereumjs/ultralight#478]
@acolytec3 @ScottyPoi ping to see.

I am looking to add Portal-Hive tests for missing edge cases, both Trin and Fluffy already support a flag like this. I am not sure if Ultralight has a storage limit yet, but a flag would be nice cause then you can simulate what happens when storage gets low.

**Comment by acolytec3** [comment]
Hmm, ok, we'll have to look and see if this is feasible.  "Should be" but we haven't touched the radius stuff in a while.

**Comment by acolytec3** [comment]
@ScottyPoi putting this on my todo list for tomorrow.  I'll need to see what `leveldb` supports.

**Comment by acolytec3** [comment]
Should be done with #593
