### ISSUE TITLE
Migrate all `eth` namespace RPC method handlers to `client/eth`

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#527]
We should migrate all of the `eth` namespace RPC message handlers in `portalnetwork` over to the `client/eth` subfolder since these are generally not network specific.  This mainly applies to the `getBlockBy...` ones currently sitting in `history/eth.ts` and then the placeholders in `state/eth.ts`.

**Comment by holgerd77** [comment]
For understanding: is an embedded light client a real Lodestar dependency with Lodestar running without logs (still wonder if we should offer this as well to run EthereumJS execution client as a logless service, so more or less in a library mode)?

**Comment by acolytec3** [comment]
Note to self, finish this up.
