### ISSUE TITLE
Add new RPC endpoints to support Beacon network data

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#528]
We should some higher level endpoints to the RPC for things like `beacon_getLightClientUpdate` and `beacon_getBootstrap` and maybe `beacon_lightClientStatus` to allow visibility into how our embedded light client is doing (i.e. is it tracking the head of the chain, etc).

**Comment by acolytec3** [comment]
@holgerd77 I'm guessing [this question](https://github.com/ethereumjs/ultralight/issues/527#issuecomment-1816997248) is related to this tracking issue maybe?  If so, then this is specifically the [lodestar light client](https://github.com/ChainSafe/lodestar/blob/unstable/packages/light-client/src/index.ts) and not the full beacon client.  It's quite light weight but it runs inside of Ultralight and essentially just listens for beacon light client data objects that are gossiped over the portal network and updates its own internal state when it finds things its looking for (i.e. light client updates and optimistic updates).

**Comment by holgerd77** [comment]
Haha, yes.

**Comment by acolytec3** [comment]
Have added:
- `beacon_getHead` - returns the capella fork Light Client Header corresponding to the current known head block
- `beacon_getFinalized` - returns the capella fork Light Client Header corresponding to the current known Finalized block

**Comment by acolytec3** [comment]
Added `beacon_getLightClientUpdate`  was added in #530

**Comment by acolytec3** [comment]
This [PR](https://github.com/ethereum/portal-network-specs/pull/322) documents all the official beacon RPC endpoints we should implement.  I think we have most of them already but should confirm against this list.

**Comment by acolytec3** [comment]
We're missing quite a few after referencing the list above.  But, we're missing lots of endpoints all around, the entire `trace` sub-namespace is missing so we should think about implementing some of these.

**Comment by acolytec3** [comment]
This is obsolete at this point so will close
