### ISSUE TITLE
Switch all hex to bytes conversions to ethjs equivalents

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#624]
Now that `@ethereumjs/util` properly supports prefixed hex string conversions by default, we should switch all of our usage from `toHexString` and `fromHexString` (imported from `@chainsafe/ssz`) to `bytesToHex` and `hexToBytes`.  Should be copy and paste (I hope.)

**Comment by ScottyPoi** [comment]
Note that these methods use `0x` prefixed hex strings.

**Comment by alivia-g** [comment]
I'll try to fix this issue : )
